import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import FetcherUsers from '@/components/utils/fetcherUsers';
import { useInfiniteQuery, useQuery } from '@tanstack/react-query';
import { useState } from 'react';
import CardUser from '@/components/ui/cardUser';
import Link from 'next/link';
const inter = Inter({ subsets: ['latin'] })

// export default function ExampleComponent() {
//   const PAGE_LIMIT = 3;

//   const fetchItems = async (key, page = 1) => {
//     const res = await fetch(`https://reqres.in/api/users?page=${page}`);
//     const data = await res.json();
//     return data;
//   };

//   const { data, isFetching, isPreviousData, fetchMore } = useQuery(['items', 1],fetchItems,
//     {
//       keepPreviousData: true,
//       staleTime: 0,
//     }
//   );

//   if (!data) {
//     return <div>Loading...</div>;
//   }

//   const handleLoadMore = () => {
//     if (!isFetching && !isPreviousData && data.length === PAGE_LIMIT) {
//       fetchMore(prevPage => prevPage + 1);
//     }
//   };
//   console.log(data)
//   return (
//     <div>
//       {data.data.map(item => (
//         <li key={item.id}>
//           <h1>{item.email}</h1>
//         </li>
//       ))}
//       <button onClick={handleLoadMore}>Load more</button>
//     </div>
//   );
// }


export default function Home() {
  const { isLoading, error, data} = useQuery(['users'], FetcherUsers);

  if (error) return <div>Error: {error.message}</div>;
  console.log(data)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className=' flex justify-center' > 
          <ul className=' w-fit grid grid-cols-2 grid-rows-2 gap-10'>
            {isLoading ? "Loading..." : ""}
            {data ? data.data.map(user => 
              <li key={user.id}>
                <Link href={`/users/${user.id}`}>
                  <CardUser data={user} />
                </Link>
              </li>
          ) :
            ""}
          </ul>
        </div>
      </main>



      {/* <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              /> */}
    </>
  )
}
